### ISSUE TITLE
ResultStream only returns first page ?

### ISSUE THREAD

**Issue by bmaz** [twitterdev/search-tweets-python#72] opened 2019-08-12 12:20 UTC
I use a Full Archive Premium account to search tweets from 2016. However, instead of receiving a list of tweets that are all different, I get a list that contains n times the same tweets. It may be due to a problem of pagination, however the number of unique tweets is 942, so higher than 500.  Here is my code : 
```
from searchtweets import ResultStream, gen_rule_payload, load_credentials

premium_search_args = load_credentials(filename="./search_tweets_creds.yaml",
                 yaml_key="search_tweets_api",
                 env_overwrite=False)
rule = gen_rule_payload("(orlando shooting OR pulse) profile_country:US",
                        from_date="2016-06-14 15:00",
                        to_date="2016-06-14 16:00",
                        results_per_call=500)
rs = ResultStream(rule_payload=rule,
                  max_results=11800,
                  max_pages=24,
                  **premium_search_args)
tweets = list(rs.stream())
```

As a result, I get a list of 11800 tweets that looks like this (with example ids) :

> id | created_at
> 1 | Tue Jun 14 15:59:59 +0000 2016
> 2 | Tue Jun 14 15:59:58 +0000 2016
> ...
> 473 | Tue Jun 14 15:57:31 +0000 2016
> 1 | Tue Jun 14 15:59:59 +0000 2016
> 2 | Tue Jun 14 15:59:58 +0000 2016
> ...
> 844 | Tue Jun 14 15:54:53 +0000 2016
> 1 | Tue Jun 14 15:59:59 +0000 2016
> ...

I used the same code last month without problem, was there any change in the API recently that could cause this ?

**Comment by igorbrigadir** [comment] 2019-08-12 15:37
Other people have reported similar problems (a larger then expected page size, and then duplicate tweets in the next page) https://twittercommunity.com/t/fullarchive-premium-search-strange-behavior-production-problem/128751 and https://twittercommunity.com/t/repetitive-next-key-for-different-pages/128776 so it's very likely it's a problem with the API and your code is fine.

**Comment by jrmontag** [comment] 2019-08-12 15:55
Thanks for opening the issues @bmaz - can you share the versions of the library and the python interpreter you're using? 

Thanks for the links @igorbrigadir, we'll will follow up on these twittercommunity posts and see what we can figure out. 

In the meantime, @bmaz, note that the 500 in your `rule_gen_payload` corresponds to the max number of tweets returned per call (page), and the max number of tweets is set by the  `max_results` param in your `ResultStream`

**Comment by bmaz** [comment] 2019-08-13 14:09
I use Anaconda 3: Python 3.7.1 and searchtweets 1.7.4

**Comment by jrmontag** [comment] 2019-08-13 17:26
Hey @bmaz, it seems like your report may be related to the API issue acknowledged here: https://twittercommunity.com/t/fullarchive-premium-search-strange-behavior-production-problem/128751/4 

Can you confirm that you are (or are not) still observing the same issue?

**Comment by bmaz** [comment] 2019-08-13 17:55
It is probably related to this issue, however I cannot test anything this month since I exceeded the 100 requests/month limitation of my account. Thank you for the link @jrmontag !

**Comment by jrmontag** [comment] 2019-08-13 20:33
No problem. I'm going to close this issue, as I suspect the linked API issue was the cause. Please feel free to open another issue in the future!

**Closed by jrmontag** 2019-08-13 20:33 UTC
