### ISSUE TITLE
JSON file in expansions ,tweet-fields , user-field , 

### ISSUE THREAD

**Issue by mnalk** [twitterdev/search-tweets-python#101] opened 2020-10-21 14:39 UTC
I think there is a problem with the JSON file when try to merge multiple files together  such as : 

1) attachments.media_keys
2)entities.mentions.username
3)eferenced_tweets.id 
4)referenced_tweets.id.author_id 

Please see this
https://stackoverflow.com/questions/64456339/how-to-flat-large-data-of-tweets-from-multiped-json-file
https://stackoverflow.com/questions/64431731/merge-multiple-json-files-into-one-file-by-using-python-stream-twitter

**Comment by jimmoffitt** [comment] 2020-11-02 21:32
Hi there,

I would like to better understand the issue you are having. Perhaps we can make some updates to how the client writes out search responses to make it even more flexible.

Currently, when writing responses... If the response has the following form:

{"data": [
  {tweet-object},{tweet-object},{tweet-object} 
],
"includes":{
     "media": [
         {media-object},{media-object},{media-object}
      ],
    "users": [
        {user-object},{user-object}
    ],
    "tweets": [
       {tweet-object}
     ]
  },
 "meta": {meta-object}
}

The client will write out the following content, as "atomic" JSON entities (each line below represents a whole, valid JSON object):
{tweet-object}
{tweet-object}
{tweet-object}
{"media":[ {media-object},{media-object},{media-object}]}
{"users":[ {user-object},{user-object}]}
{"tweets":[ {tweet-object}}
{meta-object}

When taken as together as a whole set, then these objects are not 'packaged' as one valid JSON object. 

As an alternative, there could be an option to write out the entire response as the single JSON object that is received from the endpoint...?

**Comment by jimmoffitt** [comment] 2021-01-26 23:08
Seems to be a duplicate of a related issue. Closing.

**Closed by jimmoffitt** 2021-01-26 23:08 UTC
